### ISSUE TITLE
javax.ws.rs.NotFoundException: HTTP 404 Not Found

### ISSUE THREAD

**Issue by soul2zimate** [spyrkob/manifest-component-checker#1]
I followed https://github.com/spyrkob/manifest-component-checker?tab=readme-ov-file#usage, both `pnc-url` and `manifest-url` are provided,  but the execution failed at:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Resolving [0/606]: MavenCoordinate{groupId='org.jboss.resteasy', artifactId='resteasy-json-p-provider', extension='null', classifier='null', version='6.2.7.Final-redhat-00002'}
Resolving [8/606]: MavenCoordinate{groupId='gnu.getopt', artifactId='java-getopt', extension='null', classifier='null', version='1.0.13.redhat-5'}
Resolving [5/606]: MavenCoordinate{groupId='commons-cli', artifactId='commons-cli', extension='null', classifier='null', version='1.4.0.redhat-00003'}
Resolving [7/606]: MavenCoordinate{groupId='com.sun.xml.bind.external', artifactId='rngom', extension='null', classifier='null', version='4.0.2.redhat-00001'}
Resolving [1/606]: MavenCoordinate{groupId='org.glassfish.jaxb', artifactId='jaxb-xjc', extension='null', classifier='null', version='4.0.2.redhat-00001'}
Resolving [2/606]: MavenCoordinate{groupId='io.netty', artifactId='netty-transport-classes-epoll', extension='null', classifier='null', version='4.1.108.Final-redhat-00001'}
Resolving [3/606]: MavenCoordinate{groupId='org.infinispan', artifactId='infinispan-hibernate-cache-commons', extension='null', classifier='null', version='14.0.30.Final-redhat-00001'}
Resolving [4/606]: MavenCoordinate{groupId='org.apache.activemq', artifactId='artemis-selector', extension='null', classifier='null', version='2.21.0.redhat-00052'}
Resolving [6/606]: MavenCoordinate{groupId='jakarta.servlet', artifactId='jakarta.servlet-api', extension='null', classifier='null', version='6.0.0.redhat-00006'}
Resolving [9/606]: MavenCoordinate{groupId='com.github.fge', artifactId='json-patch', extension='null', classifier='null', version='1.9.0.redhat-00002'}
Resolving [10/606]: MavenCoordinate{groupId='com.fasterxml.jackson.core', artifactId='jackson-core', extension='null', classifier='null', version='2.15.4.redhat-00001'}
Resolving [11/606]: MavenCoordinate{groupId='org.apache.lucene', artifactId='lucene-queries', extension='null', classifier='null', version='8.11.3.redhat-00001'}
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Resolving [13/606]: MavenCoordinate{groupId='org.infinispan', artifactId='infinispan-cdi-embedded-jakarta', extension='null', classifier='null', version='14.0.30.Final-redhat-00001'}
Resolving [15/606]: MavenCoordinate{groupId='jakarta.mail', artifactId='jakarta.mail-api', extension='null', classifier='null', version='2.1.3.redhat-00002'}
Resolving [14/606]: MavenCoordinate{groupId='org.apache.activemq', artifactId='artemis-jakarta-server', extension='null', classifier='null', version='2.21.0.redhat-00052'}
Resolving [17/606]: MavenCoordinate{groupId='io.netty', artifactId='netty-handler-proxy', extension='null', classifier='null', version='4.1.108.Final-redhat-00001'}
Resolving [16/606]: MavenCoordinate{groupId='com.fasterxml.woodstox', artifactId='woodstox-core', extension='null', classifier='null', version='6.4.0.redhat-00002'}
Resolving [18/606]: MavenCoordinate{groupId='com.squareup', artifactId='protoparser', extension='null', classifier='null', version='4.0.3.redhat-00001'}
Resolving [12/606]: MavenCoordinate{groupId='com.amazonaws', artifactId='jmespath-java', extension='null', classifier='null', version='1.12.284.redhat-00002'}
Resolving [19/606]: MavenCoordinate{groupId='org.jboss.eap', artifactId='wildfly-jsr77', extension='null', classifier='null', version='8.0.5.GA-redhat-00001'}
Resolving [25/606]: MavenCoordinate{groupId='org.hibernate.validator', artifactId='hibernate-validator-cdi', extension='null', classifier='null', version='8.0.1.Final-redhat-00001'}
Resolving [20/606]: MavenCoordinate{groupId='org.apache.activemq', artifactId='artemis-cli', extension='null', classifier='null', version='2.21.0.redhat-00052'}
Resolving [21/606]: MavenCoordinate{groupId='io.netty', artifactId='netty-codec-http', extension='null', classifier='null', version='4.1.108.Final-redhat-00001'}
Resolving [22/606]: MavenCoordinate{groupId='com.amazonaws', artifactId='aws-java-sdk-core', extension='null', classifier='null', version='1.12.284.redhat-00002'}
Resolving [23/606]: MavenCoordinate{groupId='org.glassfish', artifactId='jakarta.enterprise.concurrent', extension='null', classifier='null', version='3.0.0.redhat-00001'}
Resolving [24/606]: MavenCoordinate{groupId='jakarta.enterprise', artifactId='jakarta.enterprise.cdi-api', extension='null', classifier='null', version='4.0.1.redhat-00001'}
Resolving [26/606]: MavenCoordinate{groupId='org.hibernate.orm', artifactId='hibernate-envers', extension='null', classifier='null', version='6.2.26.Final-redhat-00001'}
Resolving [27/606]: MavenCoordinate{groupId='org.jboss.eap', artifactId='wildfly-clustering-infinispan-embedded-service', extension='null', classifier='null', version='8.0.5.GA-redhat-00001'}
Resolving [28/606]: MavenCoordinate{groupId='org.jboss.narayana.rts', artifactId='restat-util', extension='null', classifier='null', version='6.0.2.Final-redhat-00002'}
Resolving [29/606]: MavenCoordinate{groupId='org.jboss.eap', artifactId='wildfly-clustering-weld-web', extension='null', classifier='null', version='8.0.5.GA-redhat-00001'}
Resolving [30/606]: MavenCoordinate{groupId='org.eclipse.angus', artifactId='angus-mail', extension='null', classifier='null', version='2.0.3.redhat-00001'}
Resolving [31/606]: MavenCoordinate{groupId='org.aesh', artifactId='readline', extension='null', classifier='null', version='2.2.0.redhat-00001'}
java.lang.RuntimeException: java.lang.RuntimeException: org.jboss.pnc.client.RemoteResourceException: HTTP 404 Not Found
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:555)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:573)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:663)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:677)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:785)
	at org.jboss.set.components.ManifestVerifier.verifyComponents(ManifestVerifier.java:47)
	at org.jboss.set.components.cli.VerifyComponentsCommand.call(VerifyComponentsCommand.java:29)
	at org.jboss.set.components.cli.VerifyComponentsCommand.call(VerifyComponentsCommand.java:11)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jboss.set.components.cli.VerifyComponentsCommand.main(VerifyComponentsCommand.java:39)
Caused by: java.lang.RuntimeException: org.jboss.pnc.client.RemoteResourceException: HTTP 404 Not Found
	at org.jboss.set.components.pnc.PncManagerImpl.getArtifact(PncManagerImpl.java:42)
	at org.jboss.set.components.ManifestVerifier.lambda$verifyComponents$0(ManifestVerifier.java:55)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3101)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: org.jboss.pnc.client.RemoteResourceException: HTTP 404 Not Found
	at org.jboss.pnc.client.ArtifactClient.getAllFiltered(ArtifactClient.java:92)
	at org.jboss.set.components.pnc.PncManagerImpl.getArtifact(PncManagerImpl.java:33)
	... 11 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:247)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:217)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at jdk.proxy2/jdk.proxy2.$Proxy49.getAllFiltered(Unknown Source)
	at org.jboss.pnc.client.ArtifactClient.lambda$getAllFiltered$2(ArtifactClient.java:77)
	at org.jboss.pnc.client.DefaultRemoteCollection.<init>(DefaultRemoteCollection.java:53)
	at org.jboss.pnc.client.PageReader.getCollection(PageReader.java:40)
	at org.jboss.pnc.client.ArtifactClient.getAllFiltered(ArtifactClient.java:78)
	... 12 more``
```

**Comment by soul2zimate** [comment]
It works once I put the correct `pnc-url`
